version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-3611
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - testticketone_3611-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-3611
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy
    container_name: authproxy-3611
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice
    container_name: camundasvc-3611
    ports:
      - "0000:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager
    container_name: securitymanager-3611
    ports:
      - "0000:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway
    container_name: apigateway-3611
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - severitymaintenance
      - servicetypemaintenance
      - ticketing



  severitymaintenance: 
    build: ../../../application/services/custom_services/severitymaintenance
    image: severitymaintenance-3611
    container_name: severitymaintenance-3611
    ports: 
      - 8018:8018
    env_file: .env
    depends_on:
      - mongo

  servicetypemaintenance: 
    build: ../../../application/services/custom_services/servicetypemaintenance
    image: servicetypemaintenance-3611
    container_name: servicetypemaintenance-3611
    ports: 
      - 8019:8019
    env_file: .env
    depends_on:
      - mongo

  ticketing: 
    build: ../../../application/services/custom_services/ticketing
    image: ticketing-3611
    container_name: ticketing-3611
    ports: 
      - 8020:8020
    env_file: .env
    depends_on:
      - mongo


volumes:
  testticketone_3611-volume:
    driver: local
